server:
  type: sgv2-docsapi-service
  applicationContextPath: /
  connector:
    type: http
    port: 8182
  requestLog:
    type: external
stargate:
  bridge:
    host: localhost
    port: 8091
    useTls: false
logging:
    type: external

