version: '2'

services:
  cassandra-5:
    image: cassandra:5.0
    networks:
      - stargate
    mem_limit: 2G
    environment:
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=1024M
      - CASSANDRA_CLUSTER_NAME=c5-stargate
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 30s
      timeout: 10s
      retries: 5

  coordinator:
    image: stargateio/coordinator-4_0:${SGTAG}
    depends_on:
      cassandra-5:
        condition: service_healthy
    networks:
      - stargate
    ports:
      - "9042:9042"
      - "8081:8081"
      - "8084:8084"
      - "8085:8085"
      - "8090:8090"
      - "7000:7000"
      - "7001:7001"
      - "7199:7199"
    mem_limit: 2G
    environment:
      - JAVA_OPTS="-Xmx1536M"
      - CLUSTER_NAME=c5-stargate
      - CLUSTER_VERSION=5.0
      - SEED=cassandra-5
      - RACK_NAME=rack1
      - DATACENTER_NAME=datacenter1
      - ENABLE_AUTH=true
    healthcheck:
      test: curl -f http://localhost:8084/checker/readiness || exit 1
      interval: 15s
      timeout: 10s
      retries: 10

  restapi:
    image: stargateio/restapi:${SGTAG}
    depends_on:
      coordinator:
        condition: service_healthy
    networks:
      - stargate
    ports:
      - "8082:8082"
    mem_limit: 2G
    environment:
      - QUARKUS_GRPC_CLIENTS_BRIDGE_HOST=coordinator
      - QUARKUS_GRPC_CLIENTS_BRIDGE_PORT=8091
      - QUARKUS_HTTP_ACCESS_LOG_ENABLED=${REQUESTLOG}
      - QUARKUS_LOG_LEVEL=${LOGLEVEL}
    healthcheck:
      test: curl -f http://localhost:8082/stargate/health || exit 1
      interval: 5s
      timeout: 10s
      retries: 10

  graphqlapi:
    image: stargateio/graphqlapi:${SGTAG}
    depends_on:
      coordinator:
        condition: service_healthy
    networks:
      - stargate
    ports:
      - "8080:8080"
    mem_limit: 2G
    environment:
      - QUARKUS_GRPC_CLIENTS_BRIDGE_HOST=coordinator
      - QUARKUS_GRPC_CLIENTS_BRIDGE_PORT=8091
      - QUARKUS_HTTP_ACCESS_LOG_ENABLED=${REQUESTLOG}
      - QUARKUS_LOG_LEVEL=${LOGLEVEL}
    healthcheck:
      test: curl -f http://localhost:8080/stargate/health || exit 1
      interval: 5s
      timeout: 10s
      retries: 10

  docsapi:
    image: stargateio/docsapi:${SGTAG}
    depends_on:
      coordinator:
        condition: service_healthy
    networks:
      - stargate
    ports:
      - "8180:8180"
    mem_limit: 2G
    environment:
      - QUARKUS_GRPC_CLIENTS_BRIDGE_HOST=coordinator
      - QUARKUS_GRPC_CLIENTS_BRIDGE_PORT=8091
      - QUARKUS_HTTP_ACCESS_LOG_ENABLED=${REQUESTLOG}
      - QUARKUS_LOG_LEVEL=${LOGLEVEL}
    healthcheck:
      test: curl -f http://localhost:8180/stargate/health || exit 1
      interval: 5s
      timeout: 10s
      retries: 10

networks:
  stargate: