#!/bin/bash
#
# Copyright The Stargate Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Non-OSGi Stargate startup script

# Setup environment
BASEDIR=$(dirname "$0")
STARGATE_HOME=$(cd "$BASEDIR"; pwd)

# Java settings
if [ -z "$JAVA_HOME" ]; then
    echo "JAVA_HOME is not set. Please set JAVA_HOME to a JDK 17 installation."
    exit 1
fi

JAVA="$JAVA_HOME/bin/java"

# Check Java version
JAVA_VERSION=$("$JAVA" -version 2>&1 | head -n 1 | cut -d'"' -f2 | cut -d'.' -f1)
if [ "$JAVA_VERSION" -lt "17" ]; then
    echo "Java 17 or later is required. Found Java $JAVA_VERSION"
    exit 1
fi

# JVM options
JVM_OPTS=""
JVM_OPTS="$JVM_OPTS -Xms1G"
JVM_OPTS="$JVM_OPTS -Xmx2G"
JVM_OPTS="$JVM_OPTS -XX:+UseG1GC"
JVM_OPTS="$JVM_OPTS -XX:MaxGCPauseMillis=100"

# Stargate system properties
STARGATE_OPTS=""
STARGATE_OPTS="$STARGATE_OPTS -Dstargate.basedir=$STARGATE_HOME/data"
STARGATE_OPTS="$STARGATE_OPTS -Dlogback.configurationFile=$STARGATE_HOME/logback.xml"

# Classpath - include all jars from lib directory
CLASSPATH=""
for jar in "$STARGATE_HOME"/stargate-lib/*.jar; do
    if [ -z "$CLASSPATH" ]; then
        CLASSPATH="$jar"
    else
        CLASSPATH="$CLASSPATH:$jar"
    fi
done

# Add starter jar
CLASSPATH="$CLASSPATH:$STARGATE_HOME/stargate-starter-*.jar"

# Main class
MAIN_CLASS="io.stargate.starter.NonOsgiStarter"

# Run Stargate
echo "Starting Stargate (non-OSGi mode)..."
echo "JAVA_HOME: $JAVA_HOME"
echo "Classpath: $CLASSPATH"

exec "$JAVA" $JVM_OPTS $STARGATE_OPTS -cp "$CLASSPATH" "$MAIN_CLASS" "$@"