server:
  applicationConnectors:
    - type: http
      port: 8084
  adminConnectors:
    - type: http
      port: 8085
  requestLog:
    appenders: []

# Disable Dropwizard logging since we use external logback
logging:
  type: external