# @author Jeff Carpenter
name: Stargate Postman Collections

# runs on
# * manual trigger
on:
  workflow_dispatch:

jobs:

  # Runs Stargate Postman Collections against local Stargate instance using docker compose scripts
  automated-api-tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1

      # let all tests run, can find multiple failures in different apis
      fail-fast: false

      # props:
      # backend - cassandra backend to run
      # collection - Postman collection to run

      matrix:
        backend: [ cassandra-40 ]
        collection: [ restapi-users ]
        include:
          - backend: cassandra-40
            path: docker-compose/cassandra-4.0
          #- backend: cassandra-311
          #  path: docker-compose/cassandra-3.11
          #- backend: dse-68
          #  path: docker-compose/dse-6.8
          #- collection: docsapi-library
          #  collection-id: 12949543-caba2a02-6559-486a-9e4a-d5c0791fd296
          #  environment-id: 12949543-2e78cf27-bd8c-43f2-909f-70a2b87d65fe
          #- collection: graphqlapi-library
          #  collection-id: 17930693-65da5c64-561a-449b-a0e8-0318575f6871
          #  environment-id: 12949543-2e78cf27-bd8c-43f2-909f-70a2b87d65fe
          - collection: restapi-users
            collection-id: 17930693-47ab5f0d-407e-48cf-aa11-c51d129f1eef
            environment-id: 12949543-2e78cf27-bd8c-43f2-909f-70a2b87d65fe

    steps:
      - uses: actions/checkout@v3

      - name: Start Backend
        # Run Stargate coordinator in developer mode to save time / resources
        run: |
          cd ${{ matrix.path }}
          docker compose -f docker-compose-dev-mode.yml up -d

      - name: API access with curl
        run: |
          AUTH_TOKEN=$(docker run --rm --network cass40-stargate_stargate curlimages/curl -L -X POST 'http://coordinator:8081/v1/auth' -H 'Content-Type: application/json' --data-raw '{"username": "cassandra","password": "cassandra"}' | jq -r '.authToken')
          echo $AUTH_TOKEN
          docker run --rm --network cass40-stargate_stargate curlimages/curl -v -L 'http://restapi:8082/stargate/health'
        #docker run --rm --network cass40-stargate_stargate curlimages/curl -v -L http://restapi:8082/v2/schemas/keyspaces -H "X-Cassandra-Token: $AUTH_TOKEN" -H "Content-Type: application/json"

      - name: Stop Backend
        if: always()
        run: |
          cd ${{ matrix.path }}
          docker compose logs restapi
          docker compose -f docker-compose-dev-mode.yml down

